apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iwtp7j9pz-go 
  janus-idp.io/tekton: iwtp7j9pz-go
  backstage.io/kubernetes-id: iwtp7j9pz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iwtp7j9pz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml