apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iwtp7j9pz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iwtp7j9pz-go 
  name: iwtp7j9pz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iwtp7j9pz-go 
