apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iwtp7j9pz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:18892694317265729c99404b81ab13f2d20c6d4f@sha256:fbe060fd84fde6bc3c8f3ee6975d67219218e981bda29a276a6c1a8e9c8aca49
          name: container-image
